theme: minima
title: Robin Verbeek
description: I am a PhD Candidate at the Erasmus School of Economics. The main focus of my PhD is on mental health.

author:
  name: Robin Verbeek
  email: verbeek@ese.eur.nl

header:
  - index.md
  - research.md
  - teaching.md
  - blog.md

minima:
  skin: dark


hide_site_feed_link: true
